services:
  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  scraper:
    build:
      context: .
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=db

volumes:
  postgres_data:
